# Default configuration for SynergyX system

# Model Configuration
model:
  # Default model settings
  name: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000
  streaming: true
  
  # Provider fallback order
  provider_priority:
    - "ollama"      # Try local first
    - "openai"      # Then OpenAI-compatible
    - "azure"       # Then Azure
    - "huggingface" # Finally HuggingFace

# Memory Configuration
memory:
  max_messages: 100
  file_path: "./data/conversations.jsonl"
  auto_save: true
  
# Tool Configuration
tools:
  enabled:
    - "text_analysis"
    - "code_analysis" 
    - "data_analysis"
    - "rag"
    - "web_fetcher"
  
  text_analysis:
    sentiment_method: "rule_based"  # or "model_based"
    max_keywords: 10
    
  code_analysis:
    languages: ["python", "javascript", "java", "go"]
    max_complexity_threshold: 10
    
  data_analysis:
    max_file_size_mb: 10
    supported_formats: ["csv", "json", "xlsx"]
    
  rag:
    docs_directory: "./docs"
    index_path: "./data/rag_index"
    chunk_size: 500
    chunk_overlap: 50
    top_k: 5
    similarity_threshold: 0.7
    use_faiss: true  # fallback to sklearn if not available
    
  web_fetcher:
    timeout_seconds: 30
    max_content_length: 1000000  # 1MB
    allowed_domains: []  # empty = allow all
    user_agent: "SynergyX/0.1.0"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  title: "SynergyX API"
  description: "Advanced AI Chatbot and Analysis System"
  version: "0.1.0"
  cors_origins: ["*"]
  
# CLI Configuration  
cli:
  prompt_style: "rich"
  history_size: 1000
  auto_complete: true
  
# Benchmarking Configuration
benchmarks:
  reports_directory: "./reports"
  datasets_directory: "./data/benchmarks"
  
  # Sample sizes
  smoke_samples: 3
  full_samples: 50
  
  # Performance settings
  warmup_runs: 1
  measurement_runs: 5
  timeout_seconds: 300
  
  # Quality thresholds
  rouge_l_threshold: 0.3
  exact_match_threshold: 0.8
  groundedness_threshold: 0.7
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "./logs/synergyx.log"
  max_file_size_mb: 10
  backup_count: 5